language: node_js
node_js:
  - "6"
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: rafalnowosielski@me.com
  api_key:
    secure: WX6mmXoMSQa7U7Fifyv+8VMN9A7u0ykY3BBlc8TASNGQ7QdJULbmDiZkX0kvUh+Pu2kF002MWdqQZiiMQZEex38fiJIyECinBjkeUzh3tQDJ/OwbXLXcigYjmCW0hXeAU3owSKaJtcz6yw+BOrqn+yOnu1Vr3fIyv5M8xxZtNZMirI7HUpAz/IRzoTp3Q0ChVYMn5Q2eJO1D6HQ12wRxgdmrZlY9hj6/+yNNobBBmta2noxSnvFmu/LugvOZ5Ampk2fpNWDKtSzrdXESjQuoYgCczZEErkqQVuNYxBKFs9BxEsCWpO37bNmcMK6lsWABQARiYq9yfDTmYH4QkQRDX5GU6p6W/T068h6n9n8NKXWh2kLEyQkpJ6F2todivC1redq07dmXxn5vTDhPnPWT7PxosqaqPjz3b8snAStr8UHeX5YgNZUqL0fbUray9lZuTfzrF+D6SSBWHJvUCA+9TGWfmyMy4vfR3pHO0pHbyHNGRwUafxhhH6lA7E6BTIwWUgGMsKf0C/QDpmuMe7SmGe8wS/zP5tb+JPZ55Tr70HDY6zmQviaKXOIthcZZpJVL6WUHqb+fKK0sRz/R3MWpIcXRy4EeTaL5kIddY+nxfd33zpBO2wbHqs8NrZzSQq7fMZf3P6RpYpjudKaDY6eWD2YhSL2TXiOHqolAYuZ8x8Y=
  on:
    branch: master
notifications:
  slack:
    secure: h/gAFbJ2QTRZZVG3q31eXqsyw+g/q/kIUKSYc58WyuERHE1/7nmMetkN9ThV2ibId7/CocDedtmzfG+J624KJweSZ5eT1a4AVBXq794R9/21duSVCdp64iTrPR0KBHePmbUs0jHpLvs2smjf2oJbfBqretWs4W1unJXQHxmg+U7+riCybTegzFTxmKbu6fnN810YySJLL+6Pdamb1qntwrW9rL7NlJhCUB+uFmN0I6R76rCOzlzjRdGAZ8Kc9oOfpDVaz8oosfGRaXifDI/w7VEteQWgW3j0X9FGH/UFF2p70Bys2XFDGJ0URScNiYNOB31hWXavUZc9ZlIk+NEmvY8rm+j6dqb6bCX56zT59DHd/trvZMo7ZaLqo5ZxcrVMjI8S/vEiCshvu4xpV0S3AB6cpd6sRXeJy9Jp2SRs4DVDyo5DOuhwZna59wHHPjxCrKKU7Ts51NezMk8IiSZM1KAjB8vLYFp7Ci8DvhccCkWRb0QBMprAqXH2qckc4OM6TC3Et4dvUSvI+cvni1pdDJxHHc4PNHlZ1e/sWjfozjt0sXXvdOJBlqqXUeVX44XiyldSG+Xqa8SmXyKRMG8PEBLAbC7/xNEnGnCpkn2Dpzjft58UJ8f7ij6AX1/5bxvXJquBfPbUul4cV0igc1WXP+Jz7U8R9gcq2I1GXquT/Ls=
