language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: rafalnowosielski@me.com
  api_key:
    secure: C5q7vJ9nnR4I+Li0oDjGFEnLHGgf+V9TmReGmEkRhYMedmSztUjtXDtaPM/qEy0OLpupQ11MTSc7NmnfZgxa3/3of9zpLSmAC/QUKjzlyepa29zCt9CWGWg0A67tPEL77jp3E2rkBl4S90BJMKEy+QwNSiBXtKkAJ0KVocktNNvMcZelJAQM47QA7k3utLw+8RFXBBaz2YSWCRqWMduUMvIDoYrZAWzksTWoVime68d6kqkbHL45VXmfmfNGOtm5vZ1mrwbGxxnSHfJOcpZUD/otj5Pv507Fe57wdssZGC3r0FWMbVGJhRQvdbsrolXywpagSLu3w3lOgP1lSEEyM1tnj56DiEKJcgFIzupHehL/vo+DwGOQlmWtYLc/visDJh+fu63wGj6Lwi40ulGdQ1mNoKK44n9so2ITSW8DnoWby25KhxHtL4FfvMSlvewolF6eAo4bekVpFgNayPCiWhLfKazI7ER0cS12IibeVQNDv/7VUWgbUk2knYOv8hm+vefc1qAJ5bewPOMYtIoSGsGpNGzw78bIeWk2YenZKy/MqR7Ep/rYdP49JBr1v1jI1IL2NW0Pgd6Ax4t945A8fYZ9NW4zLe5yCnQ/Wz5/wlQpJGjxp02yGIPoClBXR73+GiD5mFjChzDFvPZKQ1NNz8cc/ORewk1zPufzQ7Zb/AE=
  on:
    branch: master
notifications:
  slack:
    secure: WlGhicjs8pnSWB0b7tX5r1aWvEZckp6U+/NcjCcg+Bh/G/feV4ZIaNZ9B3KFCjm4Rc2jPXQ1ZxeYd8OdI19mR9Jo/65MCDbnPERvc6fg0qiRwfR9uJacjHaIAJhC9Q8T/t3TZ3gXqasd1FH3aFC2gegyvHDPuV7Ou1lEyQGqgQok6iLfr8GyLkPHMFXGm/QEwlYBz+S6+TTksfBgiXk3gaxfqHKJv8+Y+M919GDW091+gWYm6FYf1t4iv46LQWFvxuYV8BKFmpXzW4PCIhl9W9D81Ek0IsZeLS5dbRG35V4FnuOBAGiGzQcytHlhdn2MpuiNPMsD1liLuKS+qEMBV9Or4KiHgedk64CnengRO0RzvxDskpNSiGTZwVYwUoJZKdiLAercWHTykKBA4vL7uuhWCM3/+iiNYiX/BrreLPDV6GWlR/qg97FlRsI+k67snRGtPqcJVQi4/uPZrRqCPk1Pz20JrudqrBL7EaMENDABkcJqobCHnQdTchFYh2nBSmLElJMLiVB1PWGJB4/K8BG9/a529M7nUH/a9juVL6vCnbD6HMm3Egnvpj6/DqUGNsYsyMvGJA26J4tqegF5qlbNvj0Bmoeguk2ZNUDGLSDIbXz7xmUxDkWO7NsQv9rsZp6FaMviN/HnuIUMSEuB8H1dt15YcJ+FHvSMxezxld8=