language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: rafalnowosielski@me.com
  api_key:
    secure: C5q7vJ9nnR4I+Li0oDjGFEnLHGgf+V9TmReGmEkRhYMedmSztUjtXDtaPM/qEy0OLpupQ11MTSc7NmnfZgxa3/3of9zpLSmAC/QUKjzlyepa29zCt9CWGWg0A67tPEL77jp3E2rkBl4S90BJMKEy+QwNSiBXtKkAJ0KVocktNNvMcZelJAQM47QA7k3utLw+8RFXBBaz2YSWCRqWMduUMvIDoYrZAWzksTWoVime68d6kqkbHL45VXmfmfNGOtm5vZ1mrwbGxxnSHfJOcpZUD/otj5Pv507Fe57wdssZGC3r0FWMbVGJhRQvdbsrolXywpagSLu3w3lOgP1lSEEyM1tnj56DiEKJcgFIzupHehL/vo+DwGOQlmWtYLc/visDJh+fu63wGj6Lwi40ulGdQ1mNoKK44n9so2ITSW8DnoWby25KhxHtL4FfvMSlvewolF6eAo4bekVpFgNayPCiWhLfKazI7ER0cS12IibeVQNDv/7VUWgbUk2knYOv8hm+vefc1qAJ5bewPOMYtIoSGsGpNGzw78bIeWk2YenZKy/MqR7Ep/rYdP49JBr1v1jI1IL2NW0Pgd6Ax4t945A8fYZ9NW4zLe5yCnQ/Wz5/wlQpJGjxp02yGIPoClBXR73+GiD5mFjChzDFvPZKQ1NNz8cc/ORewk1zPufzQ7Zb/AE=
  on:
    branch: master
notifications:
  slack:
    secure: SYojA8OMReM03MCMtFb6K4L1Rw+PpdvfXBZkO0V1o4+5T998KEp4pWkU5amtNKgs/Av5UOg7jO0XABHd4aJxaRrVKtba16jolx1UWgmY5kx52TKBO4W0ZdxGTYzsicqWcIiUmCPZWr7F2MVN5cbX4AAQnvBZbCRk2oPVWwQLDoSyKMBPeVtXc35Nplm3dG7Svbaa0gJeKfebRlN6gOCgGo4+SKUIF8die82Yq/c8kEx8i4FBxFA5lExXG5HY/b1lVXvQ4P6mYBPaaDNNyAAf6sREfQXvgkHjcquXi79RSbFSJOMe5slB36UZpB+k4NeC6rszUhUhZwHRgB+FOEG3Y6WpDfNpSgENgWN58cVd5EzGHjuaLiIY0Gf6Bt6ZapdVadhX8jOLHiY2ybAMC9sbeFMshLDyHA5ukXdvXZlKYsFhfRQ2ehy525lA3H7aqoEl/m6onbTQgLY+UCOZZUqVzAQytG2dZBHxSANPG2b4HQxe6ZZxwEeElNsL28KynjnRzpsQh9VleFxvkC7idk6XcDgtCzwB6cz6E1rlzy6luMT6epS88GG/39fEtiZzBZ52lpHHx/694acDUX5d1fNvniXtDZjtrU6bgjiNqqkPKVXl7PYDsC8DUn5gmokmosr1Vggp9dQqTjnkQDUvhDFg1SkKfnSH9Hec8LISQVc6djE=
