language: node_js
node_js:
  - "6"
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: rafalnowosielski@me.com
  api_key:
    secure: C5q7vJ9nnR4I+Li0oDjGFEnLHGgf+V9TmReGmEkRhYMedmSztUjtXDtaPM/qEy0OLpupQ11MTSc7NmnfZgxa3/3of9zpLSmAC/QUKjzlyepa29zCt9CWGWg0A67tPEL77jp3E2rkBl4S90BJMKEy+QwNSiBXtKkAJ0KVocktNNvMcZelJAQM47QA7k3utLw+8RFXBBaz2YSWCRqWMduUMvIDoYrZAWzksTWoVime68d6kqkbHL45VXmfmfNGOtm5vZ1mrwbGxxnSHfJOcpZUD/otj5Pv507Fe57wdssZGC3r0FWMbVGJhRQvdbsrolXywpagSLu3w3lOgP1lSEEyM1tnj56DiEKJcgFIzupHehL/vo+DwGOQlmWtYLc/visDJh+fu63wGj6Lwi40ulGdQ1mNoKK44n9so2ITSW8DnoWby25KhxHtL4FfvMSlvewolF6eAo4bekVpFgNayPCiWhLfKazI7ER0cS12IibeVQNDv/7VUWgbUk2knYOv8hm+vefc1qAJ5bewPOMYtIoSGsGpNGzw78bIeWk2YenZKy/MqR7Ep/rYdP49JBr1v1jI1IL2NW0Pgd6Ax4t945A8fYZ9NW4zLe5yCnQ/Wz5/wlQpJGjxp02yGIPoClBXR73+GiD5mFjChzDFvPZKQ1NNz8cc/ORewk1zPufzQ7Zb/AE=
  on:
    branch: master
notifications:
  slack:
    secure: GVXXsMwEci2qsO/81LwK0ss4MmplR/E8BAJA8RxgiZKct1+nOtU3wBgz3t0R2MAeAvHjdsmm0+LKzlSk7kIedz99DDuiqPK0g4LDOtGfHvVDHAX7Lwf9Hsvvd81QaFL58apVo6ysZaYpCKHDIUyoA3+pyo3oIbnlULRPpffeg2x8nA3AxcwiD3Jzg4JlNHKnmxx27/uLYzbjC9kNHy8i32hZhpI0dYMjqbE64PJLYgjobX4C8KNlOLxlwu76w+PEtumA3iLawZi6EO8VdgSl3hys/Dv9GxPOt9u3fPFmw6WUtK7WKGIbCZ+Az7inzUIM2pAYdUvSVqUX08iHY7WxAnjJbGEsPccPkV9gUhNfbkndUv3mdEwnHbs+E6ZRhwOpNmUg7qRUNOXlvAMzEzTruY7/BviCFkEccgljysNuAAxn2TZ2Z+WSGa4iGU3Zkv4LEfTKT+RbbIpm1zGTJ/uwtI2mAwsO7G0nHsgY9XXxdUwnWzJJINzW5X1DT8iTrlw0/0IalUOAEeMY/M5+RCv/h14ZFQjsXW2WsEGhiWGk4YCadX+PstnH0IFP5sMtZmD6KG6AaQwWN6W035AI5mGStiQ+9jJho0sP8BrtoWunM4zMgrn7h7uGYPvatZjBYjyhIudnyfJBziLNkFppWhaskcHk0yJA19L0dh4/wG2EnV4=
