language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: rafalnowosielski@me.com
  on:
    branch: master
  api_key:
    secure: HNgT6zraLGD7XywfEvtTOqxe0MhgupiV9PsofGZY4/n8BGNdkPnqWi0ZDgVTUcHdeDMd/dqpGTJVFx9+bcYEcVC/uW+08KAp0FR+OI53ORBqO9PNuWjoN0xYcqaed+b9u5UgLpDmKgnG8SlVeZpSzabLQjavCwB01HWcDdiA8B5yB/vCXTY9InWLK81/yvl/WqIOp2bIN3MjxDFEnJfkH9H/cnb69mv9m4KMNyyaTtGKb4Gi88IZqZ40L4wjJHJnTtLRBzIzjhfNXg46EkmVJ9GSAx4Wymisv/cWnry8hnfsCTaT10Vox7Tg/w9AQknGYeMH7XtNB5E9v9ovlrl3a7y0pzOLR2d99/xO2s9Wv7Hu/l+x2TaKmuUzRdLhdubC8PNat4Vh+6XZP4y8IVZLfjE5ljlqSSUZhtYK1kvY7Z6CH44uHyK7KhzCrWAME/Ox2LWoHnN8yy7cPlD/LFa9we7GIQbhnLjhO+ciT7abTf1TqIkzEr+VQ8t3OqEsHHPeNKaon19HOmOYWX3yre1y5PnNtB6mYdjsI38UMbyhkWwLji94qfP7saBV8/UJpflY5D3HouRFhkUmk6+pu0AgSxHwFBsUomJkiD2v6TWcT6qQamogHKVtDUhBOiUZha80gN7k8TXTKSdKVek4W/1fcAB6oqrlb0NbYIoSF2PGjTQ=
notifications:
  slack:
    secure: SYojA8OMReM03MCMtFb6K4L1Rw+PpdvfXBZkO0V1o4+5T998KEp4pWkU5amtNKgs/Av5UOg7jO0XABHd4aJxaRrVKtba16jolx1UWgmY5kx52TKBO4W0ZdxGTYzsicqWcIiUmCPZWr7F2MVN5cbX4AAQnvBZbCRk2oPVWwQLDoSyKMBPeVtXc35Nplm3dG7Svbaa0gJeKfebRlN6gOCgGo4+SKUIF8die82Yq/c8kEx8i4FBxFA5lExXG5HY/b1lVXvQ4P6mYBPaaDNNyAAf6sREfQXvgkHjcquXi79RSbFSJOMe5slB36UZpB+k4NeC6rszUhUhZwHRgB+FOEG3Y6WpDfNpSgENgWN58cVd5EzGHjuaLiIY0Gf6Bt6ZapdVadhX8jOLHiY2ybAMC9sbeFMshLDyHA5ukXdvXZlKYsFhfRQ2ehy525lA3H7aqoEl/m6onbTQgLY+UCOZZUqVzAQytG2dZBHxSANPG2b4HQxe6ZZxwEeElNsL28KynjnRzpsQh9VleFxvkC7idk6XcDgtCzwB6cz6E1rlzy6luMT6epS88GG/39fEtiZzBZ52lpHHx/694acDUX5d1fNvniXtDZjtrU6bgjiNqqkPKVXl7PYDsC8DUn5gmokmosr1Vggp9dQqTjnkQDUvhDFg1SkKfnSH9Hec8LISQVc6djE=
